version: "3.9"
    
services:
  db:
    image: mysql:5.7
    command: --ignore-db-dir=lost+found
    portsT:
      - 3306
    volumesT:
      - db_data:/var/lib/mysql
    restartT: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  myapp:
    depends_on:
      - db5
    buildT:
      context: ./
    ports:
      - "8000:80"
    restart: always

volumes:
  db_data: {}
